categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
prev: Prev
next: Next
comment: Comments

home: Home
archive: Archive
archives: Archives
archive_a: Archives
archive_b: 'Archives: %s'
page: Page %d
recent_posts: Recent Posts
newer: Newer
older: Older
post: Post
share: Share
powered_by: Powered by
rss_feed: RSS
category: Category
tag: Tag
date_published: Published Date

front-end developer: Front-end Developer
photographer: Photographer
runner: Runner

toggle all: Toggle All
