# Header
menu:
  Home: /
  Archives: /archives
  Apps: https://narol.pro/apps
  Github: https://github.com/narol1024
# rss: /atom.xml

# Content
excerpt_link: '> 阅读全文'

# Favicon
favicon: https://narol-blog.oss-cn-beijing.aliyuncs.com/blog-img/202406241426448.ico

# Settings toggle
settings: true

# Code CSS toggle
highlight: true

# Word count (needs hexo-wordcount)
word_count: false

# Google Analytics
google_analytics:
  enable: false
  acct: 'UA-000000000-0'

# IntenseDebate ID
intensedebate:
  enable: false
  acct: '00000000000000000000000000000000'
